# Generated by Django 4.2.5 on 2023-11-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='Food_Title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
