# Generated by Django 4.2.5 on 2023-11-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_fooditem_food_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='Food_Title',
            new_name='food_title',
        ),
    ]
